### ISSUE TITLE
Support for raspberry pi 3/4? 

### ISSUE THREAD

**Issue by CptArn** [SpoBo/dobiss2mqtt#2]
I see on docker hub there is only an amd64 version available. Any reason why there isn't support for arm/v7 like the pi's are using?

**Comment by SpoBo** [comment]
Because docker hub doesn't do this by default and I had no need for it. But it makes a lot of sense to add it. Any clue on how to add it easily ?

**Comment by SpoBo** [comment]
Ik zie dit ... https://hub.docker.com/r/ckulka/multi-arch-example maar moet mij er even in verdiepen.

**Comment by CptArn** [comment]
I've used this [this reference](https://www.docker.com/blog/getting-started-with-docker-for-arm-on-linux/)

The only things i had to do is go to docker edge version.
Make a new builder.
Rebuild the project as is and the arm versions are available. 

I've used this already to have a docker image for my pi and all seem to work fine. If you later on rebuild the project with the correct builder. There isn't anything else you need to do as far as i can see.

Let me know if you need help with this.

**Comment by SpoBo** [comment]
It should be ok. Check latest build: https://hub.docker.com/layers/vincentds/dobiss2mqtt/latest/images/sha256-6e0214aba704f265d68e8499695e221aaccc493daa75eed2a897acaaa0587d87?context=repo

I used [this article](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) and it was super easy to add. I am quite impressed with github actions. It basically does buildx in a workflow.

Go ahead & close if it appears correct to you.

**Comment by CptArn** [comment]
Docker is working now. Thanks for the fast response time!

**Comment by SpoBo** [comment]
No problem. Thx for the suggestion :)
